// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function bar(fn) {
  return Curry._1(fn, /* () */0);
}

exports.bar = bar;
/* No side effect */
